name: "05 - 1 - Event Filter and Activity Types"
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches: 
      - main
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running whenever a PR is opened/reopened/synchronized and base branch is master."

