name: 05 - 2 - Event Filters and Activity Types
on: 
  pull_request:
    types: 
      closed
    branches: 
      - master
jobs:
  echo_PR_status:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo "Running whenever a PR is closed"
          echo "Trigger: ${{ github.event_name }}"

    
